import re


abbr_to_full = {'hp': ['học phí'],
 'hphi': ['học phí'],
 'bn': ['bao nhiêu'],
 'bao nhiu': ['bao nhiêu'],
 'bao nhiê': ['bao nhiêu'],
 'bnhiu': ['bao nhiêu'],
 'z': ['vậy'],
 'dị': ['vậy'],
 'v': ['vậy'],
 'cx': ['cũng'],
 'củng': ['cũng'],
 'cũn': ['cũng'],
 'củm': ['cũng'],
 'k': ['Không'],
 'ko': ['Không'],
 'khum': ['Không'],
 'hông': ['Không'],
 'hong': ['Không'],
 'kh': ['Không'],
 'hem': ['Không'],
 'hơm': ['Không'],
 'hum': ['Không'],
 'hk': ['Không'],
 'hok': ['Không'],
 'hog': ['Không'],
 'đk': ['đúng không'],
 'đúm hông': ['đúng không'],
 'dgnl': ['đánh giá năng lực'],
 'ktx': ['ký túc xá'],
 'hb': ['học bạ', 'học bổng'],
 'hba': ['học bạ'],
 'hc bạ': ['học bạ'],
 'cntt': ['Công nghệ thông tin', 'công nghệ thông tin'],
 'j': ['gì'],
 'dì': ['gì'],
 'tr': ['trời'],
 'tròi': ['trời'],
 'chời': ['trời'],
 'cntp': ['công nghệ thực phẩm'],
 'ptxt': ['phương thức xét tuyển'],
 'xt': ['xét tuyển'],
 'dgnlcb': ['đánh giá năng lực chuyên biệt'],
 'ctsv': ['công tác sinh viên'],
 'lt': ['liên thông'],
 'ts': ['tuyển sinh'],
 'hs': ['hồ sơ', 'học sinh'],
 'dp': ['đồng phục'],
 'đp': ['đồng phục'],
 'dphuc': ['đồng phục'],
 'bhyt': ['bảo  hiểm y tế'],
 'ctdt': ['chương trình đào tạo'],
 'ctđt': ['chương trình đào tạo'],
 'tc': ['tín chỉ'],
 'tchi': ['tín chỉ'],
 'tstd': ['thí sinh tự do'],
 'tt': ['thông tin', 'thực tập'],
 'gdqp': ['giáo dục quốc phòng'],
 'tchat': ['thể chất'],
 'tn': ['tốt nghiệp'],
 'tnghiep': ['tốt nghiệp'],
 'ut': ['ưu tiên'],
 'kv': ['khu vực'],
 'vb': ['văn bằng'],
 'nna': ['ngôn ngữ anh'],
 'tsv': ['tân sinh viên'],
 'clc': ['chất lượng cao'],
 'dkxt': ['đăng ký xét tuyển'],
 'sv': ['sinh viên'],
 'hbong': ['học bổng'],
 'hoc bổng': ['học bổng'],
 'drl': ['điểm rèn luyện'],
 'đrl': ['điểm rèn luyện'],
 'th': ['tổ hợp'],
 'ctxh': ['công tác xã hội'],
 'avdv': ['anh văn đầu vào'],
 'av': ['anh văn'],
 'bt': ['biết'],
 'bít': ['biết'],
 'bc': ['biết'],
 'nma': ['nhưng mà'],
 'nnt': ['ngôn ngữ trung'],
 'nn trung': ['ngôn ngữ trung'],
 'ttgdtx': ['trung tâm giáo dục thường xuyên'],
 'gdtx': ['giáo dục thường xuyên'],
 'minhnf': ['mình'],
 'x': ['xong'],
 'xog': ['xong'],
 'đki': ['đăng kí'],
 'lun': ['luôn'],
 'mún': ['muốn'],
 'sđt': ['số điện thoại'],
 'sdt': ['số điện thoại'],
 'ntn': ['như thế nào'],
 'trg': ['trường'],
 'kq': ['kết quả'],
 'kqua': ['kết quả'],
 'dc': ['được'],
 'đc': ['được'],
 'ck': ['chuyển khoản'],
 'ckhoan': ['chuyển khoản'],
 'nv': ['nguyện vọng'],
 'nvong': ['nguyện vọng'],
 'vhvl': ['vừa học vừa làm'],
 'dttx': ['đào tạo từ xa'],
 'đttx': ['đào tạo từ xa'],
 'hc': ['học'],
 'cd': ['cao đẳng'],
 'cđ': ['cao đẳng'],
 'lp': ['lệ phí'],
 'lphi': ['lệ phí'],
 'tk': ['tài khoản'],
 'tkhoan': ['tài khoản'],
 'cdr': ['chuẩn đầu ra'],
 'cđr': ['chuẩn đầu ra'],
 'cc': ['chứng chỉ'],
 'cs': ['cơ sở'],
 'coso': ['cơ sở'],
 'ttap': ['thực tập'],
 'kt': ['kiểm tra', 'kế toán', 'kinh tế'],
 'ktr': ['kiểm tra'],
 'ktra': ['kiểm tra'],
 'kltn': ['khóa luận tốt nghiệp'],
 'datn': ['đồ án tốt nghiệp'],
 'đatn': ['đồ án tốt nghiệp'],
 'lkqt': ['liên kết quốc tế'],
 'vpd': ['văn phòng đoàn'],
 'vpđ': ['văn phòng đoàn'],
 'vpk': ['văn phòng khoa'],
 'hky': ['học kì'],
 'hki': ['học kì'],
 'tkb': ['thời khóa biểu'],
 'ht': ['hội trường'],
 'gv': ['giảng viên'],
 'bv': ['bảo vệ'],
 'e': ['em'],
 'a': ['anh'],
 'ah': ['anh'],
 'vs': ['với'],
 'ch': ['chưa'],
 'chx': ['chưa'],
 'r': ['rồi'],
 'roài': ['rồi'],
 'gòi': ['rồi'],
 'ok': ['đồng ý'],
 'okii': ['đồng ý'],
 'oke': ['đồng ý'],
 'oki la': ['đồng ý'],
 'tcnh': ['tài chính ngân hàng'],
 'lkt': ['luật kinh tế'],
 'luật kte': ['luật kinh tế'],
 'kdqt': ['kinh doanh quốc tế'],
 'nn': ['ngôn ngữ'],
 'an toàn thực phẩm': ['Đảm bảo chất lượng & ATTP'],
 'cn': ['công nghệ', 'cử nhân'],
 'cnghe': ['công nghệ'],
 'cnsh': ['công nghệ sinh học'],
 'shdk': ['sinh hoạt đầu khóa'],
 'shđk': ['sinh hoạt đầu khóa'],
 'qt': ['quản trị'],
 'kd': ['kinh doanh '],
 'tmdt': ['thương mại điện tử'],
 'cntc': ['công nghệ tài chính'],
 'attt': ['an toàn thông tin'],
 'khdl': ['khoa học dữ liệu'],
 'ks': ['kỹ sư'],
 'shcd': ['sinh hoạt công dân'],
 'htc': ['hội trường c'],
 'nckh': ['nghiên cứu khoa học'],
 'cdt': ['cơ điện tử'],
 'cđt': ['cơ điện tử'],
 'ctm': ['chế tạo máy'],
 'ttnt': ['Trí tuệ nhân tạo'],
 'khmt': ['Khoa học máy tính'],
 'tđh': ['Tự động hóa'],
 'clb': ['Câu lạc bộ'],
 'chvl': ['Cơ hội việc làm'],
 'ktmt': ['kỹ thuật môi trường'],
}

def get_abbr_and_expansion(question: str) -> str:
    """
    Phát hiện các viết tắt có trong question, trả về string:
    'abbr1: exp1, exp2; abbr2: exp3'.
    """
    found = []
    for abbr, exps in abbr_to_full.items():
        # tìm khớp nguyên từ, ko phân biệt hoa thường
        if re.search(r"\b" + re.escape(abbr) + r"\b", question, flags=re.IGNORECASE):
            found.append((abbr, exps))
    if not found:
        return ""  # hoặc 'None'
    # Ghép chuỗi phân cách bằng '; '
    return '; '.join(f"{abbr}: {', '.join(exps)}" for abbr, exps in found)

def expand_abbreviations(question: str) -> str:
    """
    Thay thế các từ viết tắt trong câu hỏi bằng cụm từ đầy đủ,
    sử dụng cụm từ đầu tiên trong danh sách tương ứng.
    """
    # Tạo một danh sách các regex để tìm từ viết tắt
    # Sắp xếp các từ viết tắt theo độ dài giảm dần để tránh thay thế từ ngắn hơn trước
    abbr_list = sorted(abbr_to_full.keys(), key=len, reverse=True)
    
    # Thực hiện thay thế
    result = question
    for abbr in abbr_list:
        # Thay thế với regex để khớp nguyên từ, giữ nguyên chữ hoa/thường
        pattern = r'\b' + re.escape(abbr) + r'\b'
        expansion = abbr_to_full[abbr][0]  # Lấy cụm từ đầu tiên
        
        # Thay thế, giữ nguyên chữ hoa/thường nếu từ viết tắt viết hoa
        result = re.sub(pattern, expansion, result, flags=re.IGNORECASE)
    
    return result
